### ISSUE TITLE
Bei Einstellung "voll" wird nicht MaxLadung gesetzt

### ISSUE THREAD

**Issue by mzwanzi** [wiggal/Docker_gen24_ladesteuerung#4]
Hallo, 

habe heute versucht die Einstellung auf "voll" zu setzen, es wurde aber nicht die MaxLadung am Wechselrichter gesetzt.

Verwendete Version: latest / 0.24.1
Einstellung Ladesteuerung: WR Schreiben und Logging

Andere Schreibänderungen im "Auto" Modus macht er ganz normal.

**Comment by wiggal** [comment]
was wurde dann gesetzt?

**Comment by mzwanzi** [comment]
er macht einfach den normalen "auto" Prozess weiter:

```
******* BEGINN: 2024-08-21 11:46:01.199744 *******

## HTTP-LADESTEUERUNG ##
>>>Parameteränderung durch WebUI-Settings: WR-Steuerung und Logging
aktuellePrognose: 2989
TagesPrognose-BattVollUm: 6366 - 14
PrognoseAbzugswert/Stunde: 628
Grundlast_Summe für Tag: 1340
aktuellePVProduktion/Watt: 1632
aktuelleEinspeisung/Watt: 325
aktuelleBatteriePower/Watt: -605
GesamtverbrauchHaus/Watt: 702
aktuelleBattKapazität/Watt: 4962
Batteriestatus in Prozent: 64.1 %
LadewertGrund: Prognoseberechnung / BatSparFaktor
Bisheriger Ladewert/Watt: 602
Neuer Ladewert/Watt: 1180

Änderung kleiner Schreibgrenze!

In SQLite-Datei gespeichert!
************* ENDE: 2024-08-21 11:46:01.203270 ************* 
```

Einstellung Ladesteuerung:
<img width="775" alt="image" src="https://github.com/user-attachments/assets/a3480fff-8d79-40d1-9950-536d933aac58">
Wechselrichter:
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/155f804b-784f-43ef-9a32-db2620ae4467">

**Comment by wiggal** [comment]
> Hallo,
> 
> habe heute versucht die Einstellung auf "voll" zu setzen, 

Mit "voll" meinst du 100%, und gesichert oder?

Und  wenn du die WebUI nochmal aufrufst, dann steht der Slider auf 100%, oder nicht?

**Comment by mzwanzi** [comment]
mit "voll" meine ich in der Ladeplanung. Da dachte ich dass er dann den MaxLadung Wert setzt (bei mir 3000). 
Ich bilde mir ein, dass das schonmal genau so funktioniert hat.

Slider steht dann auch auf 100%, aber Ladeleistung blieb auf 600W

**Comment by wiggal** [comment]
In der 0.24.1 muss die Ladeplanung so aussehen!?
![grafik](https://github.com/user-attachments/assets/72307d1d-bf78-49c3-ae86-0fe8a8e55b43)

Hast du mitbekommen, dass sich das Repository auf hub.docker.com geändert hat?

Ab Version 0.24.0 bezieht sich die Prozentangabe auf die Ladeleistung des GEN24 und nicht mehr auf MaxLadung.

**Comment by mzwanzi** [comment]
oh man, shame in me - das hab ich natürlich übersehen....

Vielen Dank für die Hilfe jetzt schaut das gut aus.

**Comment by wiggal** [comment]
No Problem.
